/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.mvbos.jegui.prev;

import br.com.mvbos.jeg.element.SelectorElement;
import br.com.mvbos.jeg.engine.JPad;
import br.com.mvbos.jeg.scene.IScene;
import br.com.mvbos.jeg.scene.ISelectorScene;
import br.com.mvbos.jeg.window.Camera;
import br.com.mvbos.jeg.window.IMemory;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import java.awt.image.BufferedImage;
import javax.swing.JPanel;

/**
 *
 * @author Marcus Becker
 */
public class PreviewWindow extends javax.swing.JFrame {

    private final IMemory[] memo;

    private final IScene scene;
    private final BufferedImage buf;
    private final Dimension dim;

    private boolean endGame;

    private final SelectorElement selectorElement = new SelectorElement(Color.WHITE, null);

    public PreviewWindow(IScene scene, IMemory[] memory, Dimension sceneDim, Dimension screenDim) {

        this.scene = scene;
        this.dim = screenDim;
        this.memo = memory;

        Camera.c().config(sceneDim.width, sceneDim.height, screenDim.width, screenDim.height);

        //cam.offSet(10, 10);
        buf = new BufferedImage(screenDim.width, screenDim.height, BufferedImage.TYPE_INT_RGB);

        //scene = createScene();
        scene.setElements(memo);
        scene.startScene();

        initComponents();

        pack();

        initGame();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        canvas = createCanvas();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        javax.swing.GroupLayout canvasLayout = new javax.swing.GroupLayout(canvas);
        canvas.setLayout(canvasLayout);
        canvasLayout.setHorizontalGroup(
            canvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 587, Short.MAX_VALUE)
        );
        canvasLayout.setVerticalGroup(
            canvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(canvas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(canvas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        endGame = true;

    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel canvas;
    // End of variables declaration//GEN-END:variables

    private JPanel createCanvas() {
        canvas = new JPanel() {

            @Override
            protected void paintComponent(Graphics gg) {
                Graphics2D g = (Graphics2D) gg;

                g.drawImage(buf, 0, 0, null);

                selectorElement.drawMe(g);
            }

            @Override
            public Dimension getPreferredSize() {
                return dim;
            }

        };

        canvas.addMouseListener(new MouseListener() {

            @Override
            public void mouseClicked(MouseEvent e) {
                JPad.p1().click(e.getX(), e.getY(), e.getButton(), e.getClickCount());
            }

            @Override
            public void mousePressed(MouseEvent e) {
                selectorElement.setEnabled(true);
                selectorElement.setPxy(e.getX(), e.getY());

                if (scene instanceof ISelectorScene) {
                    ((ISelectorScene) scene).startSelection(selectorElement);
                }
            }

            @Override
            public void mouseReleased(MouseEvent e) {

                if (scene instanceof ISelectorScene) {
                    if (selectorElement.isEnabled()) {

                        selectorElement.adjustInvertSelection();
                        selectorElement.setPx(selectorElement.getPx() + Camera.c().getCpx());
                        selectorElement.setPy(selectorElement.getPy() + Camera.c().getCpy());

                        ((ISelectorScene) scene).endSelection(selectorElement);

                    } else {
                        ((ISelectorScene) scene).endSelection(null);
                    }
                }
            }

            @Override
            public void mouseEntered(MouseEvent e) {

            }

            @Override
            public void mouseExited(MouseEvent e) {

            }
        });

        canvas.addMouseMotionListener(new MouseMotionListener() {

            @Override
            public void mouseDragged(MouseEvent e) {

                if (selectorElement.isVisible()) {
                    selectorElement.setWidth(e.getX());
                    selectorElement.setHeight(e.getY());
                }

            }

            @Override
            public void mouseMoved(MouseEvent e) {
            }

        });

        return canvas;
    }

    private IScene createScene() {
        return new DefaultScene(memo);
    }

    private void initGame() {
        new Thread() {

            @Override
            public void run() {
                long prxAtualizacao = 0;

                while (!endGame) {
                    if (System.currentTimeMillis() > prxAtualizacao) {
                        scene.updateScene();
                        scene.drawScene(buf.createGraphics());

                        canvas.repaint();

                        prxAtualizacao = System.currentTimeMillis() + 50;
                    }
                }
            }

        }.start();

    }

    public void setCamPosition(Point p) {
        Camera.c().move(p.x, p.y);
    }
}
